[project]
name = "Deep-Learning"
version = "0.1.0"
description = "Deep learning project basics"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "pydantic",
]
